// Mapa de ícone lucide (guardado no banco, kebab-case) pra um emoji real —
// usado nos cards de conteúdo (skills, bônus), onde a referência usa emoji
// colorido de verdade em vez de ícone vetorial monocromático. Ícones de
// interface (cadeado, seta, lixeira etc.) continuam com o componente
// <Icon> normal — isso é só pro "ícone temático" de cada item de conteúdo.
const ICON_TO_EMOJI: Record<string, string> = {
  accessibility: "♿",
  "alert-triangle": "⚠️",
  "arrow-up-down": "🛗",
  "book-open": "📖",
  boxes: "📦",
  "brick-wall": "🧱",
  briefcase: "💼",
  building: "🏢",
  cable: "🔌",
  calculator: "🧮",
  "calendar-clock": "🗓️",
  "check-circle-2": "✅",
  "clipboard-check": "📋",
  "clipboard-list": "📝",
  coins: "💰",
  container: "🗃️",
  database: "🗄️",
  droplet: "💧",
  droplets: "🚿",
  "file-check": "📑",
  "file-signature": "✍️",
  "file-text": "📄",
  filter: "🚰",
  flame: "🔥",
  "flask-conical": "🧪",
  gavel: "⚖️",
  "grid-3x3": "🔲",
  hammer: "🔨",
  handshake: "🤝",
  "hard-hat": "👷",
  home: "🏠",
  landmark: "🏛️",
  layers: "🗂️",
  leaf: "🌱",
  map: "🗺️",
  mountain: "⛰️",
  recycle: "♻️",
  "refresh-cw": "🔄",
  road: "🛣️",
  scale: "📏",
  "search-check": "🔍",
  "shield-alert": "🛡️",
  stamp: "🔖",
  stethoscope: "🩺",
  sun: "☀️",
  table: "📊",
  thermometer: "🌡️",
  "trending-up": "📈",
  triangle: "📐",
  truck: "🚚",
  users: "👥",
  "volume-2": "🔊",
  warehouse: "🏭",
  waves: "🌊",
  wind: "💨",
  wrench: "🔧",
  zap: "⚡",
  gift: "🎁",
  sparkles: "✨",
  rocket: "🚀",
  "folder-cog": "🗂️",
};

export function skillEmoji(iconName: string): string {
  return ICON_TO_EMOJI[iconName] ?? "🔧";
}
